"""Add missing user columns

Revision ID: 3cf38870d7c5
Revises: 457c1d627673
Create Date: 2026-02-26 21:43:54.582385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3cf38870d7c5'
down_revision: Union[str, Sequence[str], None] = '457c1d627673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('subscription_tier', sa.String(length=20), nullable=True))
    op.add_column('Users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('Users', 'LastLogin',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('IX_Users_ManagerID'), table_name='Users')
    op.create_index(op.f('ix_Users_UserID'), 'Users', ['UserID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Users_UserID'), table_name='Users')
    op.create_index(op.f('IX_Users_ManagerID'), 'Users', ['ManagerID'], unique=False)
    op.alter_column('Users', 'LastLogin',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.drop_column('Users', 'is_verified')
    op.drop_column('Users', 'is_superuser')
    op.drop_column('Users', 'subscription_tier')
    op.add_column('UserRoles', sa.Column('RoleID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('UserRoles', sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'UserRoles', type_='foreignkey')
    op.drop_constraint(None, 'UserRoles', type_='foreignkey')
    op.create_foreign_key(op.f('FK__UserRoles__RoleI__02FC7413'), 'UserRoles', 'Roles', ['RoleID'], ['RoleID'])
    op.create_foreign_key(op.f('FK__UserRoles__UserI__02084FDA'), 'UserRoles', 'Users', ['UserID'], ['UserID'])
    op.drop_column('UserRoles', 'role_id')
    op.drop_column('UserRoles', 'user_id')
    op.add_column('SalesTransactions', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('SalesTransactions', sa.Column('ProductID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('SalesTransactions', sa.Column('TransactionDate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('SalesTransactions', sa.Column('OpportunityID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('SalesTransactions', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('SalesTransactions', sa.Column('Amount', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=False))
    op.add_column('SalesTransactions', sa.Column('SalesRepID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('SalesTransactions', sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'SalesTransactions', type_='foreignkey')
    op.drop_constraint(None, 'SalesTransactions', type_='foreignkey')
    op.drop_constraint(None, 'SalesTransactions', type_='foreignkey')
    op.create_foreign_key(op.f('FK__SalesTran__Produ__59063A47'), 'SalesTransactions', 'Products', ['ProductID'], ['ProductID'])
    op.create_foreign_key(op.f('FK__SalesTran__Oppor__5812160E'), 'SalesTransactions', 'Opportunities', ['OpportunityID'], ['OpportunityID'])
    op.create_foreign_key(op.f('FK__SalesTran__Sales__59FA5E80'), 'SalesTransactions', 'Users', ['SalesRepID'], ['UserID'])
    op.drop_index(op.f('ix_SalesTransactions_TransactionID'), table_name='SalesTransactions')
    op.create_index(op.f('IX_SalesTransactions_TransactionDate'), 'SalesTransactions', ['TransactionDate'], unique=False)
    op.create_index(op.f('IX_SalesTransactions_SalesRepID'), 'SalesTransactions', ['SalesRepID'], unique=False)
    op.drop_column('SalesTransactions', 'updated_date')
    op.drop_column('SalesTransactions', 'created_date')
    op.drop_column('SalesTransactions', 'sales_rep_id')
    op.drop_column('SalesTransactions', 'transaction_date')
    op.drop_column('SalesTransactions', 'amount')
    op.drop_column('SalesTransactions', 'quantity')
    op.drop_column('SalesTransactions', 'product_id')
    op.drop_column('SalesTransactions', 'opportunity_id')
    op.add_column('SPMProcHistory', sa.Column('SqlCode', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('SPMProcHistory', sa.Column('CreatedByUserID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('SPMProcHistory', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('SPMProcHistory', sa.Column('ProcID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('SPMProcHistory', sa.Column('Version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('SPMProcHistory', sa.Column('ProcName', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'SPMProcHistory', type_='foreignkey')
    op.create_foreign_key(op.f('FK__SPMProcHi__Creat__0A9D95DB'), 'SPMProcHistory', 'Users', ['CreatedByUserID'], ['UserID'])
    op.drop_index(op.f('ix_SPMProcHistory_id'), table_name='SPMProcHistory')
    op.drop_column('SPMProcHistory', 'created_date')
    op.drop_column('SPMProcHistory', 'created_by_user_id')
    op.drop_column('SPMProcHistory', 'version')
    op.drop_column('SPMProcHistory', 'sql_code')
    op.drop_column('SPMProcHistory', 'proc_name')
    op.drop_column('SPMProcHistory', 'id')
    op.add_column('Roles', sa.Column('RoleName', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Roles', sa.Column('RoleID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('Roles', sa.Column('Description', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Roles_id'), table_name='Roles')
    op.drop_column('Roles', 'description')
    op.drop_column('Roles', 'role_name')
    op.drop_column('Roles', 'id')
    op.add_column('RolePermissions', sa.Column('RoleID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('RolePermissions', sa.Column('PermissionID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'RolePermissions', type_='foreignkey')
    op.drop_constraint(None, 'RolePermissions', type_='foreignkey')
    op.create_foreign_key(op.f('FK__RolePermi__RoleI__7E37BEF6'), 'RolePermissions', 'Roles', ['RoleID'], ['RoleID'])
    op.create_foreign_key(op.f('FK__RolePermi__Permi__7F2BE32F'), 'RolePermissions', 'Permissions', ['PermissionID'], ['PermissionID'])
    op.drop_column('RolePermissions', 'permission_id')
    op.drop_column('RolePermissions', 'role_id')
    op.add_column('Quotas', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Quotas', sa.Column('AchievedAmount', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=True))
    op.add_column('Quotas', sa.Column('Period', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Quotas', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Quotas', sa.Column('SalesRepID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Quotas', sa.Column('TargetAmount', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=False))
    op.add_column('Quotas', sa.Column('BonusRate', sa.DECIMAL(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('Quotas', sa.Column('QuotaID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'Quotas', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Quotas__SalesRep__66603565'), 'Quotas', 'Users', ['SalesRepID'], ['UserID'])
    op.drop_index(op.f('ix_Quotas_id'), table_name='Quotas')
    op.create_index(op.f('IX_Quotas_SalesRepID'), 'Quotas', ['SalesRepID'], unique=False)
    op.drop_column('Quotas', 'updated_date')
    op.drop_column('Quotas', 'created_date')
    op.drop_column('Quotas', 'bonus_rate')
    op.drop_column('Quotas', 'achieved_amount')
    op.drop_column('Quotas', 'target_amount')
    op.drop_column('Quotas', 'period')
    op.drop_column('Quotas', 'sales_rep_id')
    op.drop_column('Quotas', 'id')
    op.add_column('Products', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Products', sa.Column('ProductID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('Products', sa.Column('Description', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Products', sa.Column('ProductName', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Products', sa.Column('Price', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=False))
    op.add_column('Products', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Products_id'), table_name='Products')
    op.drop_column('Products', 'updated_date')
    op.drop_column('Products', 'created_date')
    op.drop_column('Products', 'price')
    op.drop_column('Products', 'description')
    op.drop_column('Products', 'product_name')
    op.drop_column('Products', 'id')
    op.add_column('Permissions', sa.Column('PermissionName', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Permissions', sa.Column('Description', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Permissions', sa.Column('PermissionID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_Permissions_id'), table_name='Permissions')
    op.drop_column('Permissions', 'description')
    op.drop_column('Permissions', 'permission_name')
    op.drop_column('Permissions', 'id')
    op.drop_index(op.f('ix_Opportunities_OpportunityID'), table_name='Opportunities')
    op.create_index(op.f('IX_Opportunities_OwnerID'), 'Opportunities', ['OwnerID'], unique=False)
    op.create_index(op.f('IX_Opportunities_CloseDate'), 'Opportunities', ['CloseDate'], unique=False)
    op.alter_column('Opportunities', 'UpdatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.alter_column('Opportunities', 'CreatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.drop_index(op.f('ix_LLMSpendLogs_LogID'), table_name='LLMSpendLogs')
    op.alter_column('LLMSpendLogs', 'CreatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.alter_column('LLMSpendLogs', 'Model',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('LLMSpendLogs', 'Provider',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.add_column('Interactions', sa.Column('InteractionDate', mssql.DATETIME2(), autoincrement=False, nullable=False))
    op.add_column('Interactions', sa.Column('Body', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('Channel', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Interactions', sa.Column('RecordingURL', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('OpportunityID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('Subject', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('Summary', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('RawPayload', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('InteractionType', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Interactions', sa.Column('SentimentScore', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('ExternalID', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('ActionItemsJSON', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('AccountID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('ContactID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('Direction', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Interactions', sa.Column('MeetingPlatform', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Interactions', sa.Column('InteractionID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('Interactions', sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Interactions', sa.Column('ParticipantsJSON', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Interactions', type_='foreignkey')
    op.drop_constraint(None, 'Interactions', type_='foreignkey')
    op.drop_constraint(None, 'Interactions', type_='foreignkey')
    op.drop_constraint(None, 'Interactions', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Interacti__Oppor__73BA3083'), 'Interactions', 'Opportunities', ['OpportunityID'], ['OpportunityID'])
    op.create_foreign_key(op.f('FK__Interacti__UserI__75A278F5'), 'Interactions', 'Users', ['UserID'], ['UserID'])
    op.create_foreign_key(op.f('FK__Interacti__Conta__72C60C4A'), 'Interactions', 'Contacts', ['ContactID'], ['ContactID'])
    op.create_foreign_key(op.f('FK__Interacti__Accou__74AE54BC'), 'Interactions', 'Accounts', ['AccountID'], ['AccountID'])
    op.drop_index(op.f('ix_Interactions_id'), table_name='Interactions')
    op.create_index(op.f('IX_Interactions_OpportunityDate'), 'Interactions', ['OpportunityID', 'InteractionDate'], unique=False)
    op.create_index(op.f('IX_Interactions_ContactDate'), 'Interactions', ['ContactID', 'InteractionDate'], unique=False)
    op.drop_column('Interactions', 'updated_date')
    op.drop_column('Interactions', 'created_date')
    op.drop_column('Interactions', 'participants_json')
    op.drop_column('Interactions', 'meeting_platform')
    op.drop_column('Interactions', 'recording_url')
    op.drop_column('Interactions', 'action_items_json')
    op.drop_column('Interactions', 'sentiment_score')
    op.drop_column('Interactions', 'summary')
    op.drop_column('Interactions', 'raw_payload')
    op.drop_column('Interactions', 'body')
    op.drop_column('Interactions', 'subject')
    op.drop_column('Interactions', 'interaction_date')
    op.drop_column('Interactions', 'direction')
    op.drop_column('Interactions', 'external_id')
    op.drop_column('Interactions', 'channel')
    op.drop_column('Interactions', 'interaction_type')
    op.drop_column('Interactions', 'user_id')
    op.drop_column('Interactions', 'account_id')
    op.drop_column('Interactions', 'opportunity_id')
    op.drop_column('Interactions', 'contact_id')
    op.drop_column('Interactions', 'id')
    op.add_column('CustomViews', sa.Column('SqlCode', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('CustomViews', sa.Column('CreatedByUserID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('CustomViews', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('CustomViews', sa.Column('ViewID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('CustomViews', sa.Column('ViewName', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'CustomViews', type_='foreignkey')
    op.create_foreign_key(op.f('FK__CustomVie__Creat__06CD04F7'), 'CustomViews', 'Users', ['CreatedByUserID'], ['UserID'])
    op.drop_index(op.f('ix_CustomViews_id'), table_name='CustomViews')
    op.drop_column('CustomViews', 'created_date')
    op.drop_column('CustomViews', 'created_by_user_id')
    op.drop_column('CustomViews', 'sql_code')
    op.drop_column('CustomViews', 'view_name')
    op.drop_column('CustomViews', 'id')
    op.drop_constraint(None, 'Contacts', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Contacts__Accoun__47DBAE45'), 'Contacts', 'Accounts', ['AccountID'], ['AccountID'], ondelete='CASCADE')
    op.drop_index(op.f('ix_Contacts_ContactID'), table_name='Contacts')
    op.create_index(op.f('IX_Contacts_AccountID'), 'Contacts', ['AccountID'], unique=False)
    op.alter_column('Contacts', 'UpdatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.alter_column('Contacts', 'CreatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.add_column('Commissions', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Commissions', sa.Column('RuleID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Commissions', sa.Column('Period', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Commissions', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('Commissions', sa.Column('Status', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Commissions', sa.Column('CommissionID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('Commissions', sa.Column('SalesRepID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Commissions', sa.Column('CalculatedAmount', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=False))
    op.add_column('Commissions', sa.Column('TransactionID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Commissions', sa.Column('PayoutDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Commissions', type_='foreignkey')
    op.drop_constraint(None, 'Commissions', type_='foreignkey')
    op.drop_constraint(None, 'Commissions', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Commissio__RuleI__6E01572D'), 'Commissions', 'CommissionRules', ['RuleID'], ['RuleID'])
    op.create_foreign_key(op.f('FK__Commissio__Sales__6C190EBB'), 'Commissions', 'Users', ['SalesRepID'], ['UserID'])
    op.create_foreign_key(op.f('FK__Commissio__Trans__6D0D32F4'), 'Commissions', 'SalesTransactions', ['TransactionID'], ['TransactionID'])
    op.drop_index(op.f('ix_Commissions_id'), table_name='Commissions')
    op.create_index(op.f('IX_Commissions_SalesRepID'), 'Commissions', ['SalesRepID'], unique=False)
    op.drop_column('Commissions', 'updated_date')
    op.drop_column('Commissions', 'created_date')
    op.drop_column('Commissions', 'status')
    op.drop_column('Commissions', 'payout_date')
    op.drop_column('Commissions', 'rule_id')
    op.drop_column('Commissions', 'calculated_amount')
    op.drop_column('Commissions', 'period')
    op.drop_column('Commissions', 'transaction_id')
    op.drop_column('Commissions', 'sales_rep_id')
    op.drop_column('Commissions', 'id')
    op.add_column('CommissionRules', sa.Column('UpdatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('ProductID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('Rate', sa.DECIMAL(precision=5, scale=4), autoincrement=False, nullable=False))
    op.add_column('CommissionRules', sa.Column('RuleID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.add_column('CommissionRules', sa.Column('EndDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('CreatedDate', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('RuleName', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('CommissionRules', sa.Column('StartDate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('CommissionRules', sa.Column('SalesRepID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('MinAmount', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('MaxAmount', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('CommissionRules', sa.Column('RuleType', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'CommissionRules', type_='foreignkey')
    op.drop_constraint(None, 'CommissionRules', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Commissio__Sales__60A75C0F'), 'CommissionRules', 'Users', ['SalesRepID'], ['UserID'])
    op.create_foreign_key(op.f('FK__Commissio__Produ__5FB337D6'), 'CommissionRules', 'Products', ['ProductID'], ['ProductID'])
    op.drop_index(op.f('ix_CommissionRules_id'), table_name='CommissionRules')
    op.drop_column('CommissionRules', 'updated_date')
    op.drop_column('CommissionRules', 'created_date')
    op.drop_column('CommissionRules', 'end_date')
    op.drop_column('CommissionRules', 'start_date')
    op.drop_column('CommissionRules', 'sales_rep_id')
    op.drop_column('CommissionRules', 'product_id')
    op.drop_column('CommissionRules', 'rate')
    op.drop_column('CommissionRules', 'max_amount')
    op.drop_column('CommissionRules', 'min_amount')
    op.drop_column('CommissionRules', 'rule_type')
    op.drop_column('CommissionRules', 'rule_name')
    op.drop_column('CommissionRules', 'id')
    op.drop_index(op.f('ix_Accounts_AccountID'), table_name='Accounts')
    op.alter_column('Accounts', 'UpdatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.alter_column('Accounts', 'CreatedDate',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    op.drop_column('AIAgents', 'graph_config')
    # ### end Alembic commands ###
